### PR TITLE
MNT: happi API changes

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

We're generalizing and cleaning up `happi`, so some API is changing. This adjusts `lightpath` for it.

## How Has This Been Tested?

Tested locally with dev builds until a release

attn @klauer @hhslepicka

### CODE REVIEW

**Comment by ZLLentz** [comment]
I will let this sit here until we finish the happi refactors

**Comment by klauer** [comment]
New happi is tagged; need to wait for it to get to the conda channels for tests to pass.

**Comment by klauer** [comment]
Cycled CI for new happi release 🤞

**Comment by ZLLentz** [comment]
It failed when I cycled it earlier. Never lucky!

**Comment by klauer** [comment]
😕 weird... build phase:
```
happi:                         1.5.0-py36_0            pcds-tag
```

Test phase:
```
happi-1.1.1                |           py36_0          69 KB  pcds-tag
```

**Comment by klauer** [comment]
Style check is failing the tests now.

```
$ flake8 lightpath
lightpath/controller.py:14:1: F401 'happi.loader.from_container' imported but unused
The command "flake8 lightpath" exited with 1.
```

**Pull request merged**
