### PR TITLE
MNT: Compat with Latest Happi

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Happi enforces that `name` must be a valid Python identifier now. I did a sloppy find/replace so that the tests pass again.

### CODE REVIEW

**Comment by ZLLentz** [comment]
I think there is something funky going on with loading devices with invalid fields, while loading devices with missing fields seems to be okay...

**Comment by hhslepicka** [comment]
@ZLLentz I think as long as you don't try to set the fields with an invalid value it is okay.
`save` would get the missing required fields but at instantiation it will barf if the value does not meet the required format.

**Comment by ZLLentz** [comment]
@hhslepicka then maybe the name field is special (because it is doubling as the id_ field?). Loading a database with an invalid name does not work.

**Comment by ZLLentz** [comment]
Unless some local saving is happening in this testing suite

**Pull request merged**
