### PR TITLE
MNT: Typhos

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Make it work with newest Typhos (renamed Typhon).

### CODE REVIEW

**Comment by ZLLentz** [comment]
TODO: oops I started from the wrong commit

**Comment by klauer** [comment]
Rebase doesn't look bad, at least...

**Comment by ZLLentz** [comment]
I'm assuming that what happened is that I started from an old commit without realizing it and spent a ton of time redoing work that has already been done. I'll untangle this today.

**Comment by ZLLentz** [comment]
Rebased and confirmed my previous comment. This looks clean now. Remember to never rush to write code on a Friday, you'll make mistakes and waste time.

**Pull request merged**
