### PR TITLE
MNT: noarch, shared travis config

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- make recipe noarch
- use shared travis config
- enable python>=3.8

## Motivation and Context

- related to https://github.com/pcdshub/pcds-envs/pull/158#issuecomment-758859276

### CODE REVIEW

**Comment by ZLLentz** [comment]
The build output here is very confusing. Probably something in dev-requirements.txt breaks the install, but only after switching to strict channel priority...

**Comment by klauer** [comment]
Hmm 😕  

Think you'd be up to reconsidering adding our miscellaneous, LCLS-specific dependencies to conda-forge? I have an inkling that if all the packages were there, we might be able to avoid some of these headaches.

**Comment by ZLLentz** [comment]
Oh for sure, it would probably solve a lot of related problems. For some of them I'd prefer to just eat them into pcdsdevices, though given the lack of effort on my part to actually do that it seems like a meaningless point.

**Comment by ZLLentz** [comment]
I think in this case the travis would still explode, but the full env build would be closer to passing

**Comment by ZLLentz** [comment]
for some reason, the built package here (and confirmed locally) is only installable on python 3.9... I notice the build string has a py39 in it despite being noarch. I'm a bit puzzled, I need to read some conda docs and compare recipes.

**Comment by klauer** [comment]
I've seen some of our other CI implicitly picking Python 3.9 confusingly - I can't recall details for this to be an actually useful anecdote unfortunately. 😦

**Comment by ZLLentz** [comment]
There was an error in the recipe, I was not correctly designating noarch. Hopefully this works out better.

**Pull request merged**
