### PR TITLE
BLD: rework setup.py with console entrypoint, package_data

### PR DESCRIPTION
**Pull request by klauer**
(I see no difference with this locally, may just leave this unmerged...)

Related #120

### CODE REVIEW

**Comment by ZLLentz** [comment]
May be worth merging and seeing if installed from the dev channel like this works... otherwise I think we need to find a way to make the tests show failure

**Comment by klauer** [comment]
Yeah, that's a fair point - worth a shot, at least.

**Review by ZLLentz — APPROVED** [review]
Let's try it

**Comment by ZLLentz** [comment]
This worked

**Pull request merged**
