### PR TITLE
DOC: release notes for v1.0.1

### PR DESCRIPTION
**Pull request by tangkong**
## Description
Quick bugfix tag

## Motivation and Context
get a bugfix out before the new env?

## How Has This Been Tested?
`make html` ran without issue

## Where Has This Been Documented?
This is documentation yay

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
LGTM

You can add a contributors section if you want and slot your name in

**Comment by ZLLentz** [comment]
What happened to the travis build though? It didn't even get to the running-our-code part. I'll restart that job.

**Comment by ZLLentz** [comment]
The tests passed on the previous PR so this must be a weird CI issue- maybe some random dependency or test dependency updated? I suspect we can still run `pytest` interactively without issues.

**Comment by ZLLentz** [comment]
`pytest` itself got an update on `conda-forge` like 2 hours ago, it could be related

**Comment by ZLLentz** [comment]
Possibly a packaging issue related to:
```
pytest no longer depends on the py library. pytest provides a vendored copy of py.error and py.path modules but will use the py library if it is installed. If you need other py.* modules, continue to install the deprecated py library separately, otherwise it can usually be removed as a dependency.
```

**Comment by tangkong** [comment]
Ok with a pytest pin, these tests pass.  I'm going to merge and tag

**Pull request merged**
