### PR TITLE
BLD/FIX: fix PyPI install, requirements, and setup.py

### LINKED ISSUE #124: PyPI build broken - or at least install failed
```
Collecting lightpath
  Downloading lightpath-0.6.8.tar.gz (39 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/klauer/mc/envs/lucid/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_98da0e6c668c492687da2bfd29da3ff2/setup.py'"'"'; __file__='"'"'/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_98da0e6c668c492687da2bfd29da3ff2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-pip-egg-info-i0ostscf
         cwd: /private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_98da0e6c668c492687da2bfd29da3ff2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_98da0e6c668c492687da2bfd29da3ff2/setup.py", line 4, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cb/c3/52f9622981598acc4c19fed5e4b4f80f21e5c748e6787f448abe9ad3116e/lightpath-0.6.8.tar.gz#sha256=00697803a339d4cb52133729b864ee0054f8a056d63d321927f395612d16f079 (from https://pypi.org/simple/lightpath/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading lightpath-0.6.7.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 10.5 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/klauer/mc/envs/lucid/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_8aecf72228df4f50a27bf748f2a8dcde/setup.py'"'"'; __file__='"'"'/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_8aecf72228df4f50a27bf748f2a8dcde/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-pip-egg-info-_tke3277
         cwd: /private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_8aecf72228df4f50a27bf748f2a8dcde/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_8aecf72228df4f50a27bf748f2a8dcde/setup.py", line 4, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b6/45/efc0ced37a798db7abbd9cdc6b4c2f1314b3b9d4669fba71b84efbadc243/lightpath-0.6.7.tar.gz#sha256=fc0389cd19c38a3da326c2228d2f4b671c58f9161bdc04cdf5706073bbc2dc34 (from https://pypi.org/simple/lightpath/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading lightpath-0.5.2.tar.gz (38 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/klauer/mc/envs/lucid/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_59a700cb39884b9890d0caa62e24e986/setup.py'"'"'; __file__='"'"'/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_59a700cb39884b9890d0caa62e24e986/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-pip-egg-info-bd4lbwiz
         cwd: /private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_59a700cb39884b9890d0caa62e24e986/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/pip-install-a_ux653t/lightpath_59a700cb39884b9890d0caa62e24e986/setup.py", line 4, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/48/42/c0f2d45c15a32b95ecebffd695d675b28087515cb3536ebcbb15ea80d721/lightpath-0.5.2.tar.gz#sha256=795aba98d32a1c3e72d2bf914c43d619af682d1f0b90f4e39363dd3de3af997c (from https://pypi.org/simple/lightpath/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement lightpath (from versions: 0.5.2, 0.6.7, 0.6.8)
ERROR: No matching distribution found for lightpath
```

### PR DESCRIPTION
**Pull request by klauer**
Closes #124 (I think)

### CODE REVIEW

**Comment by ZLLentz** [comment]
```
ERROR: Could not find a version that satisfies the requirement pyqt>=5 (from versions: none)
ERROR: No matching distribution found for pyqt>=5
```

**Comment by ZLLentz** [comment]
Should pass after the changes from https://github.com/pcdshub/pcdsdevices/pull/851 make it to pypi

**Comment by ZLLentz** [comment]
Python 3.9 failing due to the incompatibility with an older version of networkx that conda loves to pick for whatever reason

**Comment by klauer** [comment]
OK, happi with the diff @ZLLentz?

**Review by ZLLentz — APPROVED** [review]

**Pull request merged**
